source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
#use_frameworks!

platform :ios, "8.0"

target "DouBanFMAPIDemo" do
    pod 'TUNetworking'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'SDWebImage'
end
